### ISSUE TITLE
Django version support?

### ISSUE THREAD

**Issue by palfrey** [tutorcruncher/django-jinja-bootstrap-form#12]
README says 1.8, setup.py says 3+. Which one is it?

**Comment by tomhamiltonstubber** [comment]
1.8 is supported, do you want to add this change to your current PR?

**Comment by palfrey** [comment]
> 1.8 is supported, do you want to add this change to your current PR?

Not really. Would be good to get that merged first, then look at Django versions

**Comment by palfrey** [comment]
> 1.8 is supported, do you want to add this change to your current PR?

It doesn't seem to work with the current code base. If I install Django 1.8, [the newest django-jinja I can install](https://niwi.nz/django-jinja/latest/#_requirements) is 2.4.1. With that installed, the tests get

```
Traceback (most recent call last):
  File "/home/palfrey/src/django-jinja-bootstrap-form/testing/manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/home/palfrey/.virtualenvs/django-jinja-bootstrap-form/lib/python3.9/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/palfrey/.virtualenvs/django-jinja-bootstrap-form/lib/python3.9/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/palfrey/.virtualenvs/django-jinja-bootstrap-form/lib/python3.9/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/palfrey/.virtualenvs/django-jinja-bootstrap-form/lib/python3.9/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/palfrey/src/django-jinja-bootstrap-form/testing/../bootstrapform_jinja/apps.py", line 10, in ready
    from .templatetags import bootstrap  # NOQA
  File "/home/palfrey/src/django-jinja-bootstrap-form/testing/../bootstrapform_jinja/templatetags/bootstrap.py", line 2, in <module>
    from django.forms import BoundField, CheckboxInput, CheckboxSelectMultiple, FileInput, RadioSelect
ImportError: cannot import name 'BoundField' from 'django.forms' (/home/palfrey/.virtualenvs/django-jinja-bootstrap-form/lib/python3.9/site-packages/django/forms/__init__.py)
```
